---
# defaults file for openstack_network

controller_name: "controller"
my_management_ip: "{{ ansible_eth1.ipv4.address }}"
my_tunnel_interface_ip: "{{ ansible_eth2.ipv4.address }}"
external_interface: eth3

keystone_admin_port: 35357
keystone_port: 5000
neutron_port: 9696
