---
# defaults file for openstack_controller

controller_name: controller

mysql_root: "mysql_root"
rabbit_pass: "rabbit_pass"
keystone_dbpass: "keystone_dbpass"
admin_token: "admin_token"
admin_pass: "admin_pass"
demo_pass: "demo_pass"
