---
# handlers file for openstack_controller

- name: Sync keystone db
  shell: keystone-manage db_sync
  sudo: yes
  sudo_user: keystone
  notify:
    - Restart keystone

- name: Restart keystone
  service: name=keystone state=restarted

- name: Sync glance db
  shell: glance-manage db_sync
  sudo: yes
  sudo_user: glance
  notify:
    - Restart glance API
    - Restart glance registry

- name: Restart glance API
  service: name=glance-api state=restarted

- name: Restart glance registry
  service: name=glance-registry state=restarted

- name: Sync nova db
  shell: nova-manage db sync
  sudo: yes
  sudo_user: nova
  notify:
    - Restart nova api
    - Restart nova cert
    - Restart nova consoleauth
    - Restart nova scheduler
    - Restart nova conductor
    - Restart nova novncproxy

- name: Restart nova api
  service: name=nova-api state=restarted

- name: Restart nova cert
  service: name=nova-cert state=restarted

- name: Restart nova consoleauth
  service: name=nova-consoleauth state=restarted

- name: Restart nova scheduler
  service: name=nova-scheduler state=restarted

- name: Restart nova conductor
  service: name=nova-conductor state=restarted

- name: Restart nova novncproxy
  service: name=nova-novncproxy state=restarted

- name: Restart neutron server
  service: name=neutron-server state=restarted
