---
# handlers file for openstack_compute

- name: Restart nova compute
  service: name=nova-compute state=restarted

- name: Restart neutron plugin openvswitch agent
  service: name=neutron-plugin-openvswitch-agent state=restarted

- name: Restart openvswitch
  service: name=openvswitch-switch state=restarted