---

- hosts: all

  pre_tasks:
  - name: build hosts file
    lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_all_ipv4_addresses[1] }} {{item}}" state=present
    when: hostvars[item].ansible_all_ipv4_addresses[1] is defined
    with_items: groups.all

- hosts: controller
  roles:
    - role: openstack_controller
      mysql_root: "{{ MYSQL_ROOT }}"
      rabbit_pass: "{{ RABBIT_PASS }}"
      keystone_dbpass: "{{ KEYSTONEDB_PASS }}"
      glance_dbpass: "{{ GLANCE_DBPASS }}"
      nova_dbpass: "{{ NOVA_DBPASS }}"
      admin_token: "{{ ADMIN_TOKEN }}"
      admin_pass: "{{ ADMIN_PASS }}"
      demo_pass: "{{ DEMO_PASS }}"
      glance_pass: "{{ GLANCE_PASS }}"
      nova_pass: "{{ NOVA_PASS}}"
- hosts: network
  roles:
    - openstack_network

- hosts: compute1
  roles:
    - role: openstack_compute
      rabbit_pass: "{{ RABBIT_PASS }}"
      nova_dbpass: "{{ NOVA_DBPASS }}"
      admin_token: "{{ ADMIN_TOKEN }}"
      nova_pass: "{{ NOVA_PASS}}"
