---

- hosts: all

  pre_tasks:
  - name: build hosts file
    lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_all_ipv4_addresses[1] }} {{item}}" state=present
    when: hostvars[item].ansible_all_ipv4_addresses[1] is defined
    with_items: groups.all

- hosts: controller
  roles:
    - openstack_controller

- hosts: network
  roles:
    - openstack_network

- hosts: compute1
  roles:
    - openstack_compute
