---

- hosts: all
  pre_tasks:
  - name: update apt cache
    apt: update_cache=yes cache_valid_time=7200

- hosts: controller
  roles:
    - openstack_controller

- hosts: network
  roles:
    - openstack_network

- hosts: compute1
  roles:
    - openstack_compute
