---

- hosts: all

  pre_tasks:
  - name: build hosts file
    lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_all_ipv4_addresses[1] }} {{item}}" state=present
    when: hostvars[item].ansible_all_ipv4_addresses[1] is defined
    with_items: groups.all

- hosts: controller
  roles:
    - role: openstack_controller
      mysql_root: "{{ MYSQL_ROOT }}"
      rabbit_pass: "{{ RABBIT_PASS }}"
      admin_token: "{{ ADMIN_TOKEN }}"
      keystone_dbpass: "{{ KEYSTONEDB_PASS }}"

- hosts: network
  roles:
    - openstack_network

- hosts: compute1
  roles:
    - openstack_compute
