---
# tasks file for openstack_controller

# Add juno repos
- name: Install juno repo
  apt_repository: repo='ppa:ubuntu-cloud-archive/juno-staging'

# Update package cache
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=7200

- include: rabbitmq.yml
- include: mysql.yml
- include: keystone.yml
