---
# tasks file for openstack_controller

# Add juno repos
- name: install juno repo
  apt_repository: repo='ppa:ubuntu-cloud-archive/juno-staging'

# Update package cache
- name: update apt cache
  apt: update_cache=yes cache_valid_time=7200

# Install RabbitMQ
- name: install rabbitmq
  apt: name=rabbitmq-server state=present

# Change RabbitMQ guest password
- name: change rabbitmq guest password
  command: "rabbitmqctl change_password guest {{ RABBIT_PASS }}"
