---

- name: "Dump keystone roles"
  shell: keystone role-list
  register: role_list
  changed_when: false
  environment: openstack_service_env

- name: "Dump keystone users"
  shell: keystone user-list
  register: user_list
  changed_when: false
  environment: openstack_service_env

- name: "Dump keystone tenants"
  shell: keystone tenant-list
  register: tenant_list
  changed_when: false
  environment: openstack_service_env

- name: Create the admin tenant
  shell: keystone tenant-create --name admin --description "Admin Tenant"
  environment: openstack_service_env
  when: "tenant_list.stdout.find('admin') == -1"

- name: Create the admin user
  shell: "keystone user-create --name admin --pass {{ admin_pass }} --email admin@localhost"
  environment: openstack_service_env
  when: "user_list.stdout.find('admin') == -1"

- name: Create the admin role
  shell: keystone role-create --name admin
  environment: openstack_service_env
  when: "role_list.stdout.find('admin') == -1"

- name: "Dump admin roles in admin"
  shell: keystone user-role-list --user admin --tenant admin
  register: admin_role_list
  changed_when: false
  environment: openstack_service_env

- name: Add the admin tenant and user to the admin role
  shell: keystone user-role-add --tenant admin --user admin --role admin
  environment: openstack_service_env
  when: "admin_role_list.stdout.find('admin') == -1"

- name: Create the _member_ role
  shell: keystone role-create --name _member_
  environment: openstack_service_env
  when: "role_list.stdout.find('_member_') == -1"

- name: Add the admin tenant and user to the _member_ role
  shell: keystone user-role-add --tenant admin --user admin --role _member_
  environment: openstack_service_env
  when: "admin_role_list.stdout.find('_member_') == -1"

- name: Create the demo tenant
  shell: keystone tenant-create --name demo --description "Demo Tenant"
  environment: openstack_service_env
  when: "tenant_list.stdout.find('demo') == -1"

- name: Create the demo user
  shell: "keystone user-create --name demo --pass {{ demo_pass }} --email demo@localhost"
  environment: openstack_service_env
  when: "user_list.stdout.find('demo') == -1"

- name: "Dump demo roles in demo"
  shell: keystone user-role-list --user demo --tenant demo
  register: demo_role_list
  changed_when: false
  environment: openstack_service_env

- name: Add the demo tenant and user to the _member_ role
  shell: keystone user-role-add --tenant demo --user demo --role _member_
  environment: openstack_service_env
  when: "demo_role_list.stdout.find('_member_') == -1"

- name: Create the service tenant
  shell: keystone tenant-create --name service --description "Service Tenant"
  environment: openstack_service_env
  when: "tenant_list.stdout.find('service') == -1"
