---
# tasks file for openstack_compute

- name: Install juno repo
  apt_repository: repo='ppa:ubuntu-cloud-archive/juno-staging'

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=7200

- include: nova.yml